### PR TITLE
add WPAI information

### PR DESCRIPTION
**Pull request by joeguilmette**
@ovidiumght @Programmer095 @trey8611 when you have a moment can you review this? 

I basically ripped the HTML off our site and dumped in some of the CSS to get it to render. Things I'm concerned about:

1. Does anything I'm doing here violate the plugin repo guidelines or coding standards? I reviewed them and I think I'm good.
2. Did I miss anything? I had to change all the links and move all the images to the plugin so we aren't hotlinking, but I might have missed something and that would be bad.
3. Will this piss people off? Would it piss you off?

### CODE REVIEW

**Comment by joeguilmette** [comment]
I should probably update the readme as well, while we're at it.

**Comment by Programmer095** [comment]
@joeguilmette the first thing that jumps out is that I'd be annoyed that the links take me off my site instead of opening in a new tab.

**Review by ovidiumght — COMMENTED** [review]
Your code looks good, but I see that in the process_csv function you only check the nonce or admin referer. Shouldn't you check that the current user can create users (this is not related to this code)?

**Comment by trey8611** [comment]
I agree with @Programmer095 that the links should target _blank, but outside of that I don't see any issues, and it wouldn't annoy me. That said, it took me a minute to even find the stuff you added because it's not immediately obvious on my screen: https://d.pr/i/8FxGuQ.

**Comment by Programmer095** [comment]
Maybe we can drop the 200px of notice div top padding so it doesn't take such a high resolution to see it?: https://d.pr/i/LTkKNK

**Comment by joeguilmette** [comment]
Good call, I'll switch to vh for the padding and give the rest of it a once over for not enormous screen sizes, and change the links to open in new tab.

@ovidiumght good call on the perm issues, I'll open an issue and we can put it in this release.

**Pull request merged**
