### PR TITLE
Skip lines with all empty values (i.e. ,,,,,,,,,,)

### PR DESCRIPTION
**Pull request by mircobabini**

### CODE REVIEW

**Review by ovidiumght — APPROVED** [review]

**Comment by mircobabini** [comment]
@ovidiumght open source also means you have to communicate with contributors.

Approved yesterday, closed with no message today.
You can at least explain what's going on, right?

**Comment by joeguilmette** [comment]
Hi @mircobabini. Your repo was a bit out of date so we just manually merged it in: https://github.com/soflyy/import-users-from-csv/commit/10adf0bd6cff9a61b4323f1a8643981aec68fac6

**Comment by mircobabini** [comment]
Great! Thanks for let me (and others know).

**Comment by joeguilmette** [comment]
No problem! Thanks for your contribution!

**Pull request closed without merging**
